LineLength:
  Max: 200

Lint/UselessAssignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
