version: 2

jobs:
  rubocop:
    docker:
      - image: kakakakakku/rubocop:v0.62.0
    steps:
      - checkout
      - run: rubocop ruby/*.rb

workflows:
  version: 2
  ci:
    jobs:
      - rubocop
